<?php
/**
 * Danish wording for the results page — GENERATED by scripts/gen-labels.mjs from
 * src/lib/questions.ts. Don't edit by hand: change the question there and run
 * `npm run build:kinsta`.
 *
 * The database stores option values; these are what a human should read.
 */

declare(strict_types=1);

/** Column => { short heading, the question as it was asked }. */
const SURVEY_QUESTION_LABELS = [
    'track' => [
        'short' => 'Spor',
        'question' => 'Hvilken vej gik respondenten gennem undersøgelsen?',
    ],
    'payroll_context' => [
        'short' => 'Din hverdag',
        'question' => 'Kører du løn for din egen virksomhed — eller for andres?',
    ],
    'size' => [
        'short' => 'Antal medarbejdere',
        'question' => 'Hvor mange medarbejdere kører I løn for?',
    ],
    'b_payroll_system' => [
        'short' => 'Lønsystem',
        'question' => 'Hvilket lønsystem bruger din virksomhed primært i dag?',
    ],
    'b_frustrations' => [
        'short' => 'Frustrationer',
        'question' => 'Hvad frustrerer dig mest ved dit nuværende lønsystem?',
    ],
    'b_priorities' => [
        'short' => 'Prioriteter',
        'question' => 'Hvilke faktorer vejer du højest i et lønsystem?',
    ],
    'b_barriers' => [
        'short' => 'Skiftehindringer',
        'question' => 'Hvad er den primære årsag til, at I ikke skifter lønsystem?',
    ],
    'b_switch_intent' => [
        'short' => 'Skifteplaner',
        'question' => 'Overvejer I at skifte lønsystem inden for det næste år?',
    ],
    'a_products' => [
        'short' => 'Zenegy-produkter',
        'question' => 'Hvilke Zenegy-produkter bruger du aktivt i dag?',
    ],
    'a_migration_from' => [
        'short' => 'Tidligere system',
        'question' => 'Hvilket system kom du fra, da du valgte Zenegy?',
    ],
    'a_satisfaction' => [
        'short' => 'Tilfredshed',
        'question' => 'Hvor tilfreds er du med Zenegy i hverdagen?',
    ],
    'a_best_thing' => [
        'short' => 'Største værdi',
        'question' => 'Hvor mærker du den største værdi ved at bruge Zenegy?',
    ],
    'c_client_count' => [
        'short' => 'Antal kunder',
        'question' => 'Hvor mange virksomheder kører du løn for i dag?',
    ],
    'c_payroll_systems' => [
        'short' => 'Lønsystemer',
        'question' => 'Hvilke lønsystemer arbejder du i for dine kunder?',
    ],
    'c_setup' => [
        'short' => 'Aftalen med kunden',
        'question' => 'Hvem bestemmer lønsystemet — og hvem betaler for det?',
    ],
    'c_data_collection' => [
        'short' => 'Løndata fra kunder',
        'question' => 'Hvordan får du løndata fra dine kunder?',
    ],
    'c_frustrations' => [
        'short' => 'Tidsrøvere',
        'question' => 'Hvad tager mest tid — eller giver flest frustrationer — i lønarbejdet for dine kunder?',
    ],
    'c_priorities' => [
        'short' => 'Prioriteter',
        'question' => 'Hvad vejer tungest, når du vælger lønsystem til dine kunder?',
    ],
    'c_switch_intent' => [
        'short' => 'Skifteplaner',
        'question' => 'Overvejer du at flytte kunder til et andet lønsystem inden for det næste år?',
    ],
    'e_payslip' => [
        'short' => 'Din lønseddel',
        'question' => 'Hvor modtager du typisk din lønseddel?',
    ],
    'e_pain_points' => [
        'short' => 'Besværlige opgaver',
        'question' => 'Hvilke administrative opgaver oplever du som mest besværlige på din arbejdsplads?',
    ],
    'e_expenses' => [
        'short' => 'Udlægsregistrering',
        'question' => 'Hvis du laver et udlæg, hvor lang tid bruger du i gennemsnit på at registrere det?',
    ],
    'e_ai_trust' => [
        'short' => 'AI i løn',
        'question' => 'Hvor ville du være mest tryg ved, at en AI hjalp dig med dine løn- og arbejdsdata?',
    ],
    'ai_interest' => [
        'short' => 'AI-potentiale',
        'question' => 'Hvor ser du det største potentiale for AI i jeres administrative processer?',
    ],
    'accounting_system' => [
        'short' => 'Regnskabssystem',
        'question' => 'Hvilket regnskabs- eller ERP-system bruger I i dag?',
    ],
];

/** Column => stored value => the label the respondent actually clicked. */
const SURVEY_VALUE_LABELS = [
    'track' => [
        'zenegy' => 'Zenegy-kunde',
        'non-zenegy' => 'Andet lønsystem',
        'employee' => 'Lønmodtager',
        'bureau' => 'Lønbureau / lønadministrator',
    ],
    'payroll_context' => [
        'internal' => 'Kun for min egen virksomhed — Jeg sidder internt — direktør, HR, bogholder eller økonomiansvarlig',
        'bureau' => 'For andre virksomheder (lønadministrator) — Revisor, bogholder eller lønbureau, der kører løn for kunder',
        'both' => 'Begge dele — Både min egen virksomhed og et antal kunder',
    ],
    'size' => [
        '1-9' => '1–9',
        '10-49' => '10–49',
        '50-199' => '50–199',
        '200+' => '200+',
    ],
    'b_payroll_system' => [
        'dataloen' => 'Visma Dataløn — tidl. Bluegarden',
        'danloen' => 'Danløn',
        'lessor' => 'Lessor — by Paychex',
        'intect' => 'Intect',
        'salary' => 'Salary — nu Shine Salary',
        'dataloen-branche' => 'Dataløn Branche — tidl. ProLøn',
        'letloen' => 'LetLøn',
        'eg-loen' => 'EG Løn — EG Lønservice',
        'intega' => 'Intega Løn — tidl. Visma Løn',
        'kmd' => 'KMD Løn',
        'epos' => 'Epos — Azets',
        'excel' => 'Excel / manuelt',
        'andet' => 'Andet',
    ],
    'b_frustrations' => [
        'slow-payroll' => 'Lønkørslen tager lang tid og kræver mange manuelle tjek',
        'ui-old' => 'Brugerfladen føles gammeldags eller uoverskuelig',
        'integrations-broken' => 'Mangelfulde integrationer til bank og regnskab',
        'support-slow' => 'Support er svær at komme igennem til',
        'price-value' => 'Prisen står ikke mål med, hvad produktet kan',
        'missing-features' => 'Mangler moderne features (f.eks. app eller HR-værktøjer)',
        'manual-errors' => 'Mange manuelle trin, hvor fejl kan opstå',
        'satisfied' => 'Faktisk ingenting — jeg er tilfreds',
        'other' => 'Andet',
    ],
    'b_priorities' => [
        'ux-simplicity' => 'Enkel og intuitiv brugerflade',
        'heavy-automation' => 'Automatisering (SKAT, feriepenge, bogføring)',
        'rock-solid-support' => 'Dansk support, der svarer hurtigt',
        'open-integrations' => 'Integrationer, der synkroniserer data automatisk',
        'employee-experience' => 'Mobilapp, så medarbejderne selv kan klare udlæg/tid',
        'price' => 'Pris og gennemskuelig abonnementsstruktur',
    ],
    'b_barriers' => [
        'fear-of-transition' => 'Datamigreringen og overgangen virker uoverskuelig',
        'no-time' => 'Vi har ikke interne ressourcer eller tid til at implementere nyt',
        'risk-of-errors' => 'Bekymring for fejl eller manglende compliance under et skifte',
        'advisor-decision' => 'Det er vores eksterne revisor/bogholder, der beslutter',
        'contract-lock' => 'Vi er bundet af en kontrakt eller et større ERP-system',
        'unknown-market' => 'Vi kender ikke alternativerne godt nok',
        'happy-staying' => 'Vi er tilfredse — et skifte er ikke aktuelt',
        'other' => 'Andet',
    ],
    'b_switch_intent' => [
        'actively' => 'Ja, vi kigger aktivt på alternativer',
        'maybe' => 'Måske — det er ikke udelukket',
        'no' => 'Nej, ikke lige nu',
    ],
    'a_products' => [
        'payroll' => 'Løn — Lønkørsel, SH-dage og automatiske indberetninger',
        'numbers' => 'Numbers — Finans, bogføring og digitalt regnskab',
        'expense' => 'Expense — Udlæg, kørsel og kvitteringer',
        'time' => 'Time — Tidsregistrering, ferie og fravær',
    ],
    'a_migration_from' => [
        'dataloen' => 'Visma Dataløn — tidl. Bluegarden',
        'danloen' => 'Danløn',
        'lessor' => 'Lessor — by Paychex',
        'intect' => 'Intect',
        'salary' => 'Salary — nu Shine Salary',
        'dataloen-branche' => 'Dataløn Branche — tidl. ProLøn',
        'letloen' => 'LetLøn',
        'eg-loen' => 'EG Løn — EG Lønservice',
        'intega' => 'Intega Løn — tidl. Visma Løn',
        'kmd' => 'KMD Løn',
        'epos' => 'Epos — Azets',
        'excel' => 'Excel / manuelt',
        'startup' => 'Direkte til Zenegy',
        'andet' => 'Andet',
    ],
    'a_satisfaction' => [
        'very-unhappy' => 'Meget utilfreds',
        'unhappy' => 'Ikke tilfreds',
        'meh' => 'Det går',
        'happy' => 'Tilfreds',
        'very-happy' => 'Meget tilfreds',
    ],
    'a_best_thing' => [
        'time-saving' => 'Jeg sparer markant tid på lønkørslen',
        'automation' => 'Automatisk indberetning (SKAT, feriepenge m.m.)',
        'integrations' => 'Det spiller sammen med mine andre systemer og min bank',
        'ui-ux' => 'Platformen er moderne og nem at arbejde i',
        'support' => 'Jeg får hurtig og kompetent hjælp, når jeg har brug for det',
        'all-in-one' => 'Alt er samlet ét sted (løn + Numbers + HR)',
    ],
    'c_client_count' => [
        '1-5' => '1–5 kunder',
        '6-20' => '6–20 kunder',
        '21-50' => '21–50 kunder',
        '51-100' => '51–100 kunder',
        '100+' => 'Over 100 kunder',
    ],
    'c_payroll_systems' => [
        'dataloen' => 'Visma Dataløn — tidl. Bluegarden',
        'danloen' => 'Danløn',
        'lessor' => 'Lessor — by Paychex',
        'intect' => 'Intect',
        'salary' => 'Salary — nu Shine Salary',
        'dataloen-branche' => 'Dataløn Branche — tidl. ProLøn',
        'letloen' => 'LetLøn',
        'eg-loen' => 'EG Løn — EG Lønservice',
        'intega' => 'Intega Løn — tidl. Visma Løn',
        'kmd' => 'KMD Løn',
        'epos' => 'Epos — Azets',
        'zenegy' => 'Zenegy',
        'excel' => 'Excel / manuelt',
        'andet' => 'Andet',
    ],
    'c_setup' => [
        'we-choose-we-pay' => 'Vi vælger systemet og har abonnementet — Vi fakturerer kunden for lønnen — kunden ser sjældent systemet',
        'we-choose-client-pays' => 'Vi vælger systemet, kunden har abonnementet — Kunden betaler selv, men følger vores anbefaling',
        'client-chose' => 'Kunden har valgt systemet — Vi arbejder i det, kunden allerede har',
        'mixed' => 'Det er helt forskelligt fra kunde til kunde — Ingen fast model',
    ],
    'c_data_collection' => [
        'email-excel' => 'På mail — typisk et Excel-ark eller en besked',
        'client-portal' => 'Kunden taster selv ind i lønsystemet eller en portal',
        'time-system' => 'Automatisk fra et tidsregistreringssystem',
        'messages' => 'Telefon, SMS eller løse beskeder',
        'paper' => 'Papir, scannede sedler eller PDF\'er',
        'i-collect' => 'Jeg finder og taster det selv ud fra bilag og systemer',
        'other' => 'Andet',
    ],
    'c_frustrations' => [
        'chasing-data' => 'At jage løndata og svar hos kunderne inden deadline',
        'many-systems' => 'At skulle arbejde i flere forskellige lønsystemer',
        'switching-clients' => 'Skift mellem kunder, logins og faner',
        'client-onboarding' => 'At sætte nye kunder op — lønarter, overenskomst og pension',
        'no-bulk-actions' => 'Manglende massehandlinger — jeg gentager det samme kunde for kunde',
        'approval-trail' => 'Godkendelse og dokumentation af, hvad kunden har godkendt',
        'reconciliation' => 'Afstemning og bogføring af lønnen i regnskabssystemet',
        'employee-questions' => 'Spørgsmål fra kundernes medarbejdere',
        'price-margin' => 'Prisen pr. lønseddel presser min indtjening',
        'other' => 'Andet',
    ],
    'c_priorities' => [
        'one-login' => 'Ét login og overblik på tværs af alle kunder',
        'bulk-actions' => 'Massehandlinger — flere kunder klaret i ét flow',
        'client-self-service' => 'At kunden selv leverer og godkender løndata',
        'integrations' => 'Automatisk bogføring og integration til regnskabssystemet',
        'expert-support' => 'Support med lønfaglig viden, når reglerne er svære',
        'partner-economics' => 'Pris og marginer på partneraftalen',
        'easy-onboarding' => 'Nem opsætning og migrering af en ny kunde',
        'compliance' => 'Sikkerhed, GDPR og revisionsspor',
    ],
    'c_switch_intent' => [
        'actively-consolidating' => 'Ja — jeg leder efter ét system til så mange kunder som muligt',
        'actively-some' => 'Ja — for enkelte kunder',
        'maybe' => 'Måske — det er ikke udelukket',
        'no' => 'Nej, ikke lige nu',
    ],
    'e_payslip' => [
        'app' => 'I en app eller medarbejderportal',
        'email' => 'Som PDF på email',
        'eboks' => 'I e-Boks / Mit.dk',
        'paper' => 'På print / papir',
    ],
    'e_pain_points' => [
        'expense-pain' => 'Gemme kvitteringer og afregne udlæg/kørsel manuelt',
        'time-pain' => 'Tidsregistrering eller at logge ferie og fravær',
        'payslip-confusing' => 'Min lønseddel er svær at tyde',
        'no-mobile-access' => 'Mangel på en app — jeg skal klare alt fra en computer',
        'none' => 'Ingen — det fungerer fint',
    ],
    'e_expenses' => [
        'seconds' => 'Få sekunder — et billede i en app, så er det klaret',
        'minutes' => 'Et par minutter — en formular online',
        'heavy-process' => 'Længere — gemme kvittering, printe eller sende mail',
        'not-relevant' => 'Ikke relevant — jeg har ikke udlæg',
    ],
    'e_ai_trust' => [
        'checking' => 'Til at tjekke min lønseddel for fejl (f.eks. manglende tillæg)',
        'input' => 'Til at læse mine kvitteringer, så jeg slipper for at indtaste beløb',
        'assistant' => 'Som assistent, der forklarer regler om ferie eller barsel',
        'none' => 'Jeg vil ikke have AI i mine løn- eller fraværsdata',
    ],
    'ai_interest' => [
        'anomaly-detection' => 'Automatisk fejlsøgning og kontrol inden lønnen godkendes',
        'data-entry' => 'Automatisk bogføring og matchning af udlæg/kvitteringer',
        'support-answers' => 'Besvarelse af interne spørgsmål om ferie og regler',
        'not-ready' => 'Vi er ikke klar til AI i lønprocessen endnu',
    ],
    'accounting_system' => [
        'e-conomic' => 'e-conomic',
        'dinero' => 'Dinero',
        'billy' => 'Billy — nu Shine',
        'uniconta' => 'Uniconta',
        'visma-bc' => 'Visma Business',
        'microsoft-bc' => 'Business Central',
        'zenegy-numbers' => 'Zenegy Numbers',
        'andet' => 'Andet',
    ],
];
