/**
 * Produces the two files that get uploaded to Kinsta.
 *
 * Vite already inlines the whole site into one index.html. This does the same
 * for the PHP: the modules under kinsta/api/ are concatenated into a single
 * api.php, in dependency order, with their `<?php`, `declare` and `require_once`
 * lines stripped. The modules stay separate in the repo (and stay testable);
 * api.php is a build artifact, exactly like the JS bundle.
 *
 * Result:
 *   dist/index.html   the survey, assets and fonts inlined
 *   dist/api.php      config + validation + database + request handling
 *   dist/results.php  the internal results view (WordPress login required)
 *   dist/share.png    link-preview image, referenced absolutely by the meta tags
 *
 * Nothing else is left in dist/, so "upload everything in dist/" is two files.
 */
import { readFile, writeFile, readdir, rm } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const apiDir = join(root, 'kinsta', 'api')
const dist = join(root, 'dist')

// Dependency order: helpers first, dispatch last (it runs on include).
const BUNDLES = {
  'api.php': ['config.php', 'columns.php', 'db.php', 'respond.php', 'main.php'],
  'results.php': ['config.php', 'db.php', 'results-page.php'],
}

function stripModuleHeader(source) {
  return source
    .replace(/^<\?php\s*/, '')
    .replace(/^declare\(strict_types=1\);\s*/m, '')
    .replace(/^require_once .*;\s*$/gm, '')
    .trim()
}

for (const [outputName, modules] of Object.entries(BUNDLES)) {
  const parts = []
  for (const name of modules) {
    const source = await readFile(join(apiDir, name), 'utf8')
    parts.push(`// ── ${name} ${'─'.repeat(Math.max(0, 60 - name.length))}\n\n${stripModuleHeader(source)}`)
  }
  await writeFile(join(dist, outputName), `<?php
/**
 * Zenegy survey — generated by scripts/build-kinsta.mjs. Do not edit here.
 * The sources are kinsta/api/*.php; rebuild with \`npm run build:kinsta\`.
 */

declare(strict_types=1);

${parts.join('\n\n')}
`)
}

// Inline the favicon so the upload stays at two files.
const favicon = await readFile(join(root, 'public', 'favicon.svg'), 'utf8')
const dataUri = `data:image/svg+xml;base64,${Buffer.from(favicon).toString('base64')}`
const indexPath = join(dist, 'index.html')
const html = await readFile(indexPath, 'utf8')
await writeFile(indexPath, html.replace(/href="[^"]*favicon\.svg"/, `href="${dataUri}"`))

// Anything else Vite copied from public/ isn't referenced — drop it so what's
// left in dist/ is exactly what belongs on the server. share.png stays: link
// previews need a real file at a real URL, they can't read a data URI.
const KEEP = new Set(['index.html', 'api.php', 'results.php', 'share.png'])
for (const entry of await readdir(dist, { withFileTypes: true })) {
  if (KEEP.has(entry.name)) continue
  await rm(join(dist, entry.name), { recursive: true, force: true })
}

const size = (await readFile(indexPath)).byteLength
console.log(`dist/index.html  ${(size / 1024).toFixed(0)} kB (assets inlined)`)
for (const name of Object.keys(BUNDLES)) {
  console.log(`dist/${name.padEnd(12)} ${((await readFile(join(dist, name))).byteLength / 1024).toFixed(0)} kB`)
}
console.log('dist/share.png   link-preview image')
