/**
 * Generates kinsta/api/labels.php — the Danish wording for the results page.
 *
 * The survey stores option *values* (`we-choose-client-pays`), which is right for
 * analysis and useless to read. The labels already exist in src/lib/questions.ts,
 * so they're extracted from there rather than retyped: bundle the questions
 * module with rolldown (stubbing the logo imports, which Node can't load), read
 * every question, and write the map out as PHP.
 *
 * Run by `npm run build:kinsta`. Commit the generated file — the deploy doesn't
 * need Node on the server.
 */
import { rolldown } from 'rolldown'
import { mkdtemp, writeFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

/**
 * Which question each database column stores. The survey's answer keys and its
 * question ids deliberately differ (b1 → b_payroll_system), so the pairing has
 * to be stated once — here.
 */
const COLUMN_TO_QUESTION = {
  payroll_context: 'context',
  size: 'size',
  b_payroll_system: 'b1',
  b_frustrations: 'b2',
  b_priorities: 'b3',
  b_barriers: 'b4',
  b_switch_intent: 'b5',
  a_products: 'a1',
  a_migration_from: 'a1_migration',
  a_satisfaction: 'a2',
  a_best_thing: 'a3',
  c_client_count: 'c1',
  c_payroll_systems: 'c2',
  c_setup: 'c3',
  c_data_collection: 'c4',
  c_frustrations: 'c5',
  c_priorities: 'c6',
  c_switch_intent: 'c7',
  e_payslip: 'e1',
  e_pain_points: 'e2',
  e_expenses: 'e3',
  e_ai_trust: 'e4',
  ai_interest: 'ai',
  accounting_system: 'numbers',
}

/** `track` isn't a question — it's derived from the path the respondent took. */
const TRACK_LABELS = {
  zenegy: 'Zenegy-kunde',
  'non-zenegy': 'Andet lønsystem',
  employee: 'Lønmodtager',
  bureau: 'Lønbureau / lønadministrator',
}

const stubAssets = {
  name: 'stub-assets',
  resolveId(id) {
    return /\.(svg|png|jpe?g|otf|woff2?|css)$/.test(id) ? { id, external: false } : null
  },
  load(id) {
    return /\.(svg|png|jpe?g|otf|woff2?|css)$/.test(id) ? 'export default ""' : null
  },
}

const dir = await mkdtemp(join(tmpdir(), 'survey-labels-'))
try {
  const bundle = await rolldown({
    input: join(root, 'src/lib/questions.ts'),
    plugins: [stubAssets],
    platform: 'node',
  })
  await bundle.write({ dir, format: 'esm', entryFileNames: 'questions.mjs' })
  await bundle.close()

  const questions = await import(join(dir, 'questions.mjs'))
  const { getQuestionSequence } = questions

  // Every path, so questions that only appear on one of them are covered too.
  const paths = [
    { is_employee: true },
    { is_employee: false, payroll_context: 'internal', track: 'zenegy' },
    { is_employee: false, payroll_context: 'internal', track: 'non-zenegy' },
    { is_employee: false, payroll_context: 'bureau', c_payroll_systems: ['zenegy'] },
    { is_employee: false, payroll_context: 'bureau', c_payroll_systems: ['dataloen'] },
  ]
  const byId = new Map()
  for (const args of paths) {
    for (const question of getQuestionSequence(args)) {
      if (!byId.has(question.id)) byId.set(question.id, question)
    }
  }

  const headings = { track: { short: 'Spor', question: 'Hvilken vej gik respondenten gennem undersøgelsen?' } }
  const values = { track: TRACK_LABELS }
  const subLabels = {}
  for (const [column, questionId] of Object.entries(COLUMN_TO_QUESTION)) {
    const question = byId.get(questionId)
    if (!question) {
      console.warn(`gen-labels: no question "${questionId}" for column ${column}`)
      continue
    }
    headings[column] = { short: question.shortLabel ?? question.question, question: question.question }
    const map = {}
    const subs = {}
    for (const option of question.options ?? []) {
      map[option.value] = option.label
      if (option.subLabel) subs[option.value] = option.subLabel
    }
    if (Object.keys(map).length) values[column] = map
    if (Object.keys(subs).length) subLabels[column] = subs
  }

  const php = (value, indent) => {
    const pad = ' '.repeat(indent)
    const entries = Object.entries(value).map(([k, v]) =>
      typeof v === 'string'
        ? `${pad}'${k.replace(/'/g, "\\'")}' => '${v.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}',`
        : `${pad}'${k}' => [\n${php(v, indent + 4)}\n${pad}],`)
    return entries.join('\n')
  }

  await writeFile(join(root, 'kinsta/api/labels.php'), `<?php
/**
 * Danish wording for the results page — GENERATED by scripts/gen-labels.mjs from
 * src/lib/questions.ts. Don't edit by hand: change the question there and run
 * \`npm run build:kinsta\`.
 *
 * The database stores option values; these are what a human should read.
 */

declare(strict_types=1);

/** Column => { short heading, the question as it was asked }. */
const SURVEY_QUESTION_LABELS = [
${php(headings, 4)}
];

/** Column => stored value => the label the respondent actually clicked. */
const SURVEY_VALUE_LABELS = [
${php(values, 4)}
];

/** The smaller print under an option, where the survey showed one. */
const SURVEY_VALUE_SUBLABELS = [
${php(subLabels, 4)}
];
`)
  console.log(`Generated kinsta/api/labels.php (${Object.keys(headings).length} questions)`)
} finally {
  await rm(dir, { recursive: true, force: true })
}
